### ISSUE TITLE
Some questions about the code.

### ISSUE THREAD

**Issue by Yuxin-CV** [Epiphqny/CondInst#3]
Hi~ @Epiphqny 
Thanks for your code ~ I run your code and have some questions about your implementation.

1. The mask tower part is not consist with the paper.
https://github.com/Epiphqny/CondInst/blob/ea3f717fce73a8e4c273f1379c9d9c3550387e1b/fcos/modeling/fcos/fcos.py#L163
I think it should be 4 x conv with num_channel = 128. 
Your implementation is 8 x conv with num_channel = 256.

2. The weight of mask tower is not initiated.
https://github.com/Epiphqny/CondInst/blob/ea3f717fce73a8e4c273f1379c9d9c3550387e1b/fcos/modeling/fcos/fcos.py#L217-L221

3. After I correct 1 & 2, I found that the result is quite poor...
As I mentioned in https://github.com/aim-uofa/AdelaiDet/issues/39
 I also found that the loss of cls & reg is higher than FCOS. So I am interested in the loss behavior & Box AP of your R-101-3x experiment. Can you share some helpful information with me? Because it is quite strange that the Box AP is degenerated in my experiment, it should be benefit from the multi-task training.

**Comment by Yuxin-CV** [comment]
BTW, I wonder the batch_size, the num_GPU and the GPU type(GPU memory) you use in your experiment(37.1 mask AP).

**Comment by YuqingWang1029** [comment]
@Yuxin-CV Total batchsize of 24 on 8 GPUs(v100, 32G)

**Comment by Yuxin-CV** [comment]
> @Yuxin-CV Total batchsize of 24 on 8 GPUs(v100, 32G)

Thanks for your reply. @Epiphqny 
I think I find a bug in your implementation, detailed in https://github.com/aim-uofa/AdelaiDet/issues/39

**Comment by YuqingWang1029** [comment]
@Yuxin-CV Thanks for your attention, but nowadays I have no time to improve the code, you can report the bugs here and I'll correct and train it in the future.

**Comment by ziwei-zh** [comment]
How do you solve the problem #2? Since I find no definitions for  self.cls_tower and self.bbox_tower.
@Yuxin-CV

**Comment by sdsy888** [comment]
> How do you solve problem #2? Since I find no definitions for self.cls_tower and self.bbox_tower.
> @Yuxin-CV

@Epiphqny Hi，I just found the same problem with what @ziwei-zh mentioned above. Could you tell us about the implementation of `self.cls_tower and self.bbox_tower.`? 
Thank you.

**Comment by Yuxin-CV** [comment]
> How do you solve the problem #2? Since I find no definitions for  self.cls_tower and self.bbox_tower.
> @Yuxin-CV 

The code of CondInst is released at AdelaiDet.
