### ISSUE TITLE
Where is the pre-trained weights?

### ISSUE THREAD

**Issue by xllau** [Epiphqny/CondInst#5]
Sorry to ask where is the pre-trained weights, I cannot find it in the README.

**Comment by YuqingWang1029** [comment]
@xllau Because the code has been modified, I deleted the old weights. I have upload the new weights now in https://drive.google.com/file/d/17-g91zwJzt99G8APza0IaleWYLC3kTMK/view?usp=sharing , if there is still any problem, please let me now.

**Comment by xllau** [comment]
> @xllau Because the code has been modified, I deleted the old weights. I have upload the new weights now in https://drive.google.com/file/d/17-g91zwJzt99G8APza0IaleWYLC3kTMK/view?usp=sharing , if there is still any problem, please let me now.

Got it! Thanks a lot!
